name: ShutDown
version: 0.0.2
author: l1npengtul
main: me.l1npengtul.shutdown.shutdown
commands:
  shutdown:
      description: ShutDown the server and saves all.
      usage: /<command>
      permission: <command>.shutdown
      permission-message: You cant shutdown the server!